export const CONSTANT = {
  SUCCESS: 'Success',
  SERVER_RUNNING: 'Server is running',
  SERVER_ERROR: 'Server Error',
  REASON: 'reason',
  INFO: 'info',
  DEVELOPMENT: 'development',
  PRODUCTION: 'production',
  CREATE: 'CREATE',
  READ: 'READ',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  USER: 'User',
  OTP: 'Otp',
  CHURCH: 'Church',
  EVENT: 'Event',
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  RESET_PASSWORD: 'RESET_PASSWORD',
  VERIFY_EMAIL: 'VERIFY_EMAIL',
  TEST: 'test',
  INVALID_BASE_URL: 'Invalid base URL',
  INVALID_DATABASE_URL: 'Invalid database URL',
  UNHANDLED_REJECTION: 'Unhandled Rejection',
  NOT_FOUND: 'Not Found',
  AUTHENTICATION_ERROR: 'Authentication Error',
  PERMISSION_DENIED: 'Permission Denied',
  DATABASE_ERROR: 'Database Error',
  NETWORK_ERROR: 'Network Error',
  VALIDATION_ERROR: 'Validation Error',
  DUPLICATE_ERROR: 'Duplicate Error',
  MISSING_FIELD: 'Missing Field',
  INVALID_FIELD: 'Invalid Field',
  EXPIRED_TOKEN: 'Expired Token',
  INVALID_TOKEN: 'Invalid Token',
  MISSING_TOKEN: 'Missing Token',
  UNAUTHORIZED_ACCESS: 'Unauthorized Access',
  FORBIDDEN: 'Forbidden',
  INTERNAL_SERVER_ERROR: 'Internal Server Error',
  BAD_GATEWAY: 'Bad Gateway',
  SERVICE_UNAVAILABLE: 'Service Unavailable',
}

export const LOGGER = {
  LOG_LEVEL: 'info',
  LOG_DATE: 'YYYY-MM-DD HH:mm:ss',
  LOG_FILE_NAME: 'combined.log',
}
export const tokenTypes = {
  ACCESS: 'access',
  REFRESH: 'refresh',
  RESET_PASSWORD: 'resetPassword',
  VERIFY_EMAIL: 'verifyEmail',
}

export const ROUTE = {
  ROOT: '/',
  ID: '/:id',
  CHURCH: '/church',
  DOCS: '/docs',
  SIGN_IN: '/auth/signin',
  SIGN_UP: '/auth/signup',
  FORGOT_PASSWORD: '/auth/forgot-password',
  RESET_PASSWORD: '/auth/reset-password',
  VERIFY_EMAIL: '/auth/verify-email',
  USERS: '/users',
  USERS_ID: '/users/:id',
  USERS_SORT: '/users?sort=:sortField&limit=:limit&page=:page',
  OTPS: '/otps',
  OTPS_ID: '/otps/:id',
  CHURCHES: '/churches',
  CHURCHES_ID: '/churches/:id',
  CHURCHES_SORT: '/churches?sort=:sortField&limit=:limit&page=:page',
  EVENTS: '/events',
  EVENTS_ID: '/events/:id',
  EVENTS_SORT: '/events?sort=:sortField&limit=:limit&page=:page',
  EVENTS_PAGINATION: '/events?page=:pageNumber&pageSize=:pageSize',
}

export const MESSAGES = {
  USER: {
    SUCCESS: {
      CREATE: 'User created successfully',
      READ: 'User retrieved successfully',
      UPDATE: 'User updated successfully',
      DELETE: 'User deleted successfully',
      SIGN_IN: 'Sign-in successful',
      SIGN_UP: 'Sign-up successful',
      FORGOT_PASSWORD: 'Forgot password link sent successfully',
      RESET_PASSWORD: 'Password reset successful',
      VERIFY_EMAIL: 'Email verification link sent successfully',
    },
    ERROR: {
      CREATE: 'Failed to create user',
      READ: 'Failed to retrieve user',
      UPDATE: 'Failed to update user',
      DELETE: 'Failed to delete user',
      SIGN_IN: 'Failed to sign in',
      SIGN_UP: 'Failed to sign up',
      FORGOT_PASSWORD: 'Failed to send forgot password link',
      RESET_PASSWORD: 'Failed to reset password',
      VERIFY_EMAIL: 'Failed to send email verification link',
    },
    CANNOT_CHANGE_EMAIL: 'Change of email is not allowed!',
    PAGINATION_ERROR: 'Pagination error: Invalid page number or page size',
    DATA_LENGTH_ERROR: 'Data length error: Data length exceeds the limit',
    AUTH_ERROR: 'Authentication error: Invalid credentials',
    VALIDATION_ERROR: 'Validation error: Invalid data format',
    DATABASE_ERROR: 'Database error: Operation failed due to database issue',
    SERVER_ERROR: 'Server error: Unexpected error occurred on the server',
    NETWORK_ERROR: 'Network error: Failed to connect to the server',
  },
  OTP: {
    SUCCESS: {
      CREATE: 'Otp created successfully',
      READ: 'Otp retrieved successfully',
      UPDATE: 'Otp updated successfully',
      DELETE: 'Otp deleted successfully',
    },
    ERROR: {
      CREATE: 'Failed to create otp',
      READ: 'Failed to retrieve otp',
      UPDATE: 'Failed to update otp',
      DELETE: 'Failed to delete otp',
    },
    VALIDATION_ERROR: 'Otp validation error: Invalid format',
    DATABASE_ERROR: 'Otp database error: Operation failed due to database issue',
  },
  CHURCH: {
    SUCCESS: {
      CREATE: 'Church created successfully',
      READ: 'Church retrieved successfully',
      UPDATE: 'Church updated successfully',
      DELETE: 'Church deleted successfully',
    },
    ERROR: {
      CREATE: 'Failed to create church',
      READ: 'Failed to retrieve church',
      UPDATE: 'Failed to update church',
      DELETE: 'Failed to delete church',
    },
    PERMISSION_ERROR: 'Permission error: You do not have permission to perform this action',
    DATABASE_ERROR: 'Church database error: Operation failed due to database issue',
  },
  EVENT: {
    SUCCESS: {
      CREATE: 'Event created successfully',
      READ: 'Event retrieved successfully',
      UPDATE: 'Event updated successfully',
      DELETE: 'Event deleted successfully',
    },
    ERROR: {
      CREATE: 'Failed to create event',
      READ: 'Failed to retrieve event',
      UPDATE: 'Failed to update event',
      DELETE: 'Failed to delete event',
    },
    DUPLICATE_ERROR: 'Duplicate event error: Event with the same details already exists',
    DATABASE_ERROR: 'Event database error: Operation failed due to database issue',
  },
  AUTH: {
    SUCCESS: {
      SIGN_IN: 'Sign-in successful',
      SIGN_UP: 'Sign-up successful',
      FORGOT_PASSWORD: 'Forgot password link sent successfully',
      RESET_PASSWORD: 'Password reset successful',
      VERIFY_EMAIL: 'Email verification link sent successfully',
    },
    ERROR: {
      SIGN_IN: 'Failed to sign in',
      SIGN_UP: 'Failed to sign up',
      FORGOT_PASSWORD: 'Failed to send forgot password link',
      RESET_PASSWORD: 'Failed to reset password',
      VERIFY_EMAIL: 'Failed to send email verification link',
    },
    EXPIRED_TOKEN_ERROR: 'Token expired error: The authentication token has expired',
    INVALID_TOKEN_ERROR: 'Token invalid error: The authentication token is invalid',
    MISSING_TOKEN_ERROR: 'Token missing error: No authentication token provided',
    DATABASE_ERROR: 'Authentication database error: Operation failed due to database issue',
    SERVER_ERROR: 'Authentication server error: Unexpected error occurred on the server',
    NETWORK_ERROR: 'Authentication network error: Failed to connect to the server',
  },
  VALIDATION_ERROR: 'Validation error: Invalid data format',
  DATABASE_ERROR: 'Database error: Operation failed due to database issue',
  SERVER_ERROR: 'Server error: Unexpected error occurred on the server',
  NETWORK_ERROR: 'Network error: Failed to connect to the server',
  CANNOT_CHANGE_EMAIL: 'Change of email is not allowed!',
  
}
